### ISSUE TITLE
Verify 3061 Libraries/Template

### ISSUE THREAD

**Issue by rguinn-frc** [FRC1732/2024-Protobot#2]
AC:

- Can map joystick/button panel buttons to commands
- gyro works and can be reset reliably
- Can drive the robot field-centric
- Odometry is correct after driving for a little (start at known location, drive around, go back to location, ensure values are roughly the same)
- Stable shuffleboard (shuffleboard robot code crash must no longer be reproducible) 
- Logging works (advantagekit), ideally using the sdcard, can ftp into robot over wifi to retrieve files
- Robot can follow basic pathplanner path in auto mode
- Optional: Odometry refresh from apriltag works

**Comment by MaxCStone** [comment]
Finished:

-Robot can be driven field-centric (we may want to remove the ability to toggle between the field and robot centric)
-Gyro works and can be reset
-mapping joystick and button panels
-logging works (remote access etc)

**Comment by rguinn-frc** [comment]
I'm marking this as done assuming 

- Stable shuffleboard (shuffleboard robot code crash must no longer be reproducible)

is done
